steps:
  # Create zip file containing function source code
  - name: 'alpine'
    dir: 'cloud-function'
    args: ['sh', '-c', 'ls -la && apk add zip && zip function.zip ./main.py ./requirements.txt']

  # Deploy to Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'cloud-function'
    args:
    - gcloud
    - functions
    - deploy
    - function-1-v10
    - --gen2
    - --runtime=python39
    - --region=us-central1
    - --source=function.zip
    - --trigger-http
    - --entry-point=function_1_v10
    - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
timeout: '1800s' 