steps:
  # Create zip file containing function source code
  - name: 'debian'
    args: ['bash', '-c', 'apt-get update && apt-get install -y zip && zip -r function.zip main.py requirements.txt']

  # Deploy to Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - function-1-v10
    - --gen2
    - --runtime=python39
    - --region=us-central1
    - --source=function.zip
    - --trigger-http
    - --entry-point=function_1_v10
    - --allow-unauthenticated
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/'
    paths: ['function.zip']

# Specify the Cloud Storage bucket for logs
logsBucket: 'gs://devops-442409_cloudbuild/logs'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1800s'
  logging: CLOUD_LOGGING_ONLY