steps:
  # Deploy to Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - function-1-v10
    - --gen2
    - --runtime=python39
    - --region=us-central1
    - --source=function-source
    - --trigger-http
    - --entry-point=function_1_v10
    - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY